# Generated by Django 4.2 on 2023-08-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='', max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_jp', models.CharField(blank=True, default='', max_length=200)),
                ('describe', models.TextField(blank=True, default='', max_length=1000)),
                ('photo', models.ImageField(upload_to='pokemon')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('appeared_at', models.DateTimeField()),
                ('disappeared_at', models.DateTimeField()),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('heath', models.IntegerField(blank=True, default=100, null=True)),
                ('strength', models.IntegerField(blank=True, default=0, null=True)),
                ('defense', models.IntegerField(blank=True, default=0, null=True)),
                ('stamina', models.IntegerField(blank=True, default=0, null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon')),
            ],
        ),
    ]
